### PR TITLE
src/im-application-list.c: Add tooltip support.

### PR DESCRIPTION
**Pull request by sunweaver**

### CODE REVIEW

**Comment by sunweaver** [comment]
@flexiondotorg It would be nice to get your feedback on this as a English native speaker. Thanks.

**Comment by sunweaver** [comment]
@tari01: Unit tests are failing for this one. As a-i-messages is one of your favourite indicators and you are much more familiar with it, can you adjust the tooltip message and fix the unit tests (see above thoughts on tooltip naming, etc.).

**Review by flexiondotorg — APPROVED** [review]
LGTM

**Comment by tari01** [comment]
@sunweaver 

Aaargh...! You undid my unit test fix. Will push it on top of this again.

**Review by tari01 — APPROVED** [review]

**Pull request merged**
